DROP TABLE Polaganje;
DROP TABLE Komisija;
DROP TABLE Ispit;
DROP TABLE Evidencija;
DROP TABLE Cas;
DROP TABLE Pohadja;
DROP TABLE KursInstrumentalni;
DROP TABLE KursVokalni;
DROP TABLE KursTeorijski;
DROP TABLE Kurs;
DROP TABLE Ucionica;
DROP TABLE Filijala;
DROP TABLE Stalni;
DROP TABLE Honorarni;
DROP TABLE Nastavnik;
DROP TABLE Odrasli;
DROP TABLE Dete;
DROP TABLE Polaznik;
DROP TABLE Staratelj;
DROP TABLE Telefon;
DROP TABLE Osoba;

CREATE TABLE Osoba (
    jmbg VARCHAR2(13) PRIMARY KEY,
    ime VARCHAR2(255) NOT NULL,
    prezime VARCHAR2(255) NOT NULL,
    adresa VARCHAR2(255) NOT NULL,
    mail VARCHAR2(255) NOT NULL
);

CREATE TABLE Telefon ( 
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brojTelefona VARCHAR2(15) NOT NULL,
    jmbg VARCHAR2(13) NOT NULL,
    CONSTRAINT uk_broj_jmbg UNIQUE (brojTelefona, jmbg),
    FOREIGN KEY (jmbg) REFERENCES Osoba(jmbg)
);

CREATE TABLE Staratelj (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jmbg_osobe VARCHAR2(13) UNIQUE NOT NULL,
    FOREIGN KEY (jmbg_osobe) REFERENCES Osoba(jmbg)
);

CREATE TABLE Nastavnik (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jmbg_osobe VARCHAR2(13) UNIQUE NOT NULL,
    strucnaSprema VARCHAR2(255) NOT NULL,
    datumZaposlenja DATE NOT NULL,
    FOREIGN KEY (jmbg_osobe) REFERENCES Osoba(jmbg)
);

CREATE TABLE Honorarni (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nastavnik_id NUMBER NOT NULL UNIQUE,
    brUgovora VARCHAR2(255) NOT NULL,
    brCasovaMesecno INT NOT NULL,
    trajanjeUgovora DATE NOT NULL,
    FOREIGN KEY (nastavnik_id) REFERENCES Nastavnik(id)
);

CREATE TABLE Stalni (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nastavnik_id NUMBER NOT NULL UNIQUE,
    jmbgMentora VARCHAR2(13),
    radnoVreme VARCHAR2(255) NOT NULL,
    statusMentora NUMBER(1) NOT NULL,
    FOREIGN KEY (nastavnik_id) REFERENCES Nastavnik(id),
    FOREIGN KEY (jmbgMentora) REFERENCES Osoba(jmbg)
);

CREATE TABLE Polaznik (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jmbg_osobe VARCHAR2(13) UNIQUE NOT NULL,
    FOREIGN KEY (jmbg_osobe) REFERENCES Osoba(jmbg)
);

CREATE TABLE Odrasli (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polaznik_id NUMBER NOT NULL UNIQUE,
    zanimanje VARCHAR2(255) NOT NULL,
    FOREIGN KEY (polaznik_id) REFERENCES Polaznik(id)
);

CREATE TABLE Dete (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polaznik_id NUMBER NOT NULL UNIQUE,
    datumRodjenja DATE NOT NULL,
    brojDosijea VARCHAR2(255) NOT NULL,
    staratelj_id NUMBER NOT NULL,
    FOREIGN KEY (polaznik_id) REFERENCES Polaznik(id),
    FOREIGN KEY (staratelj_id) REFERENCES Staratelj(id)
);

CREATE TABLE Filijala (
    idFilijale VARCHAR2(255) PRIMARY KEY,
    adresa VARCHAR2(255) NOT NULL,
    radnoVreme VARCHAR2(255) NOT NULL,
    opremljenostUcionica VARCHAR2(255) NOT NULL,
    kapacitetFilijale INTEGER NOT NULL
);

CREATE TABLE Kurs (
    idKursa VARCHAR2(255) PRIMARY KEY,
    idFilijale VARCHAR2(255) NOT NULL,
    nastavnik_id NUMBER NOT NULL,
    naziv VARCHAR2(255) NOT NULL,
    nivo VARCHAR2(20) CHECK (nivo IN ('pocetni', 'srednji', 'napredni')),
    tipNastave VARCHAR2(20) CHECK (tipNastave IN ('individualna', 'grupna')),
    FOREIGN KEY (idFilijale) REFERENCES Filijala(idFilijale),
    FOREIGN KEY (nastavnik_id) REFERENCES Nastavnik(id)
);

CREATE TABLE Ispit (
    idIspita VARCHAR2(255) PRIMARY KEY,
    idKursa VARCHAR2(255) NOT NULL,
    datum DATE NOT NULL,
    FOREIGN KEY (idKursa) REFERENCES Kurs(idKursa)
);

CREATE TABLE Komisija (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nastavnik_id NUMBER NOT NULL,
    idIspita VARCHAR2(255) NOT NULL,
    CONSTRAINT uk_komisija UNIQUE (nastavnik_id, idIspita),
    FOREIGN KEY (nastavnik_id) REFERENCES Nastavnik(id),
    FOREIGN KEY (idIspita) REFERENCES Ispit(idIspita)
);

CREATE TABLE KursInstrumentalni (
    idKursa VARCHAR2(255) PRIMARY KEY,
    instrumenti VARCHAR2(255) NOT NULL,
    FOREIGN KEY (idKursa) REFERENCES Kurs(idKursa)
);

CREATE TABLE KursTeorijski (
    idKursa VARCHAR2(255) PRIMARY KEY,
    nazivPredmeta VARCHAR2(255) NOT NULL,
    FOREIGN KEY (idKursa) REFERENCES Kurs(idKursa)
);

CREATE TABLE KursVokalni (
    idKursa VARCHAR2(255) PRIMARY KEY,
    tipPevanja VARCHAR2(50) CHECK (tipPevanja IN ('individualno', 'horsko')),
    FOREIGN KEY (idKursa) REFERENCES Kurs(idKursa)
);

CREATE TABLE Pohadja (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polaznik_id NUMBER NOT NULL,
    idKursa VARCHAR2(255) NOT NULL,
    CONSTRAINT uk_pohadja UNIQUE (polaznik_id, idKursa),
    FOREIGN KEY (polaznik_id) REFERENCES Polaznik(id),
    FOREIGN KEY (idKursa) REFERENCES Kurs(idKursa)
);

CREATE TABLE Polaganje (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polaznik_id NUMBER NOT NULL,
    idIspita VARCHAR2(255) NOT NULL,
    ocena INT NOT NULL,
    polozio NUMBER(1) NOT NULL,
    CONSTRAINT uk_polaganje UNIQUE (polaznik_id, idIspita),
    FOREIGN KEY (polaznik_id) REFERENCES Polaznik(id),
    FOREIGN KEY (idIspita) REFERENCES Ispit(idIspita)
);

CREATE TABLE Ucionica (
    idUcionice VARCHAR2(255) PRIMARY KEY,
    idFilijale VARCHAR2(255) NOT NULL,
    oznaka VARCHAR2(255) NOT NULL,
    kapacitetUcionice INTEGER NOT NULL,
    FOREIGN KEY (idFilijale) REFERENCES Filijala(idFilijale)
);

CREATE TABLE Cas (
    idCasa VARCHAR2(255) PRIMARY KEY,
    idKursa VARCHAR2(255) NOT NULL,
    idUcionice VARCHAR2(255) NOT NULL,
    datum DATE NOT NULL,
    vreme VARCHAR2(255) NOT NULL,
    lekcija VARCHAR2(255) NOT NULL,
    FOREIGN KEY (idKursa) REFERENCES Kurs(idKursa),
    FOREIGN KEY (idUcionice) REFERENCES Ucionica(idUcionice)
);

CREATE TABLE Evidencija (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polaznik_id NUMBER NOT NULL,
    idCasa VARCHAR2(255) NOT NULL,
    ocena INT NOT NULL,
    prisustvo NUMBER(1) NOT NULL,
    CONSTRAINT uk_evidencija UNIQUE (polaznik_id, idCasa),
    FOREIGN KEY (polaznik_id) REFERENCES Polaznik(id),
    FOREIGN KEY (idCasa) REFERENCES Cas(idCasa)
);
